update formatting

diff --git a/AUTOSKY/AutoSky1 b/AUTOSKY/AutoSky1
--- a/AUTOSKY/AutoSky1
+++ b/AUTOSKY/AutoSky1
@@ -15,16 +15,18 @@ WX=${BASEDIR}
 Xresult=99
 
 #
-cd $WX ;
+cd $WX
 #
 
 # IS AUTOSKY ENABLED?
-if [ ! -e $ENABLEFILE ] ; then
-     exit -90
+if [ ! -e $ENABLEFILE ]; then
+   echo "Not enabled!"
+   echo "AutoSky1 done."
+   exit -90
 fi
 
 # PULL THE INFORMATION FROM NWS
-/usr/bin/wget --no-check-certificate  alerts.weather.gov/cap/$OFILE  2>/dev/null
+/usr/bin/wget --no-check-certificate alerts.weather.gov/cap/$OFILE 2>/dev/null
 
 # COPY THE WEIRD NAMED FILE TO SOMETHING NORMAL
 $CP -f $OFILE $NFILE1
@@ -36,103 +38,107 @@ $RM -f $OFILE
 #   SET TCONTROL TO "0" (zero) FOR PRODUCTION MODE
 # PARAMETER IS SET ON THE CALL OF AutoSky1, i.e. ./AutoSky1 [1-9]
 
-if [ -z $1 ] ; then
-     TCONTROL=0
-   else
-     TCONTROL=$1
+if [ -z $1 ]; then
+   TCONTROL=0
+else
+   TCONTROL=$1
 fi
 
 case $TCONTROL in
 
-     0)
-        echo 1 > /dev/null
-        ;;
-     1)
-        # Tornado Watch / Tornado Warning
-        echo "Running Test #1: Tornado Watch / Tornado Warning..."
-        $CP -f test.file1 $NFILE1
-        ;;
-     2)
-        # Tornado Watch / Winter WX Adv / Tornado Watch / Red Flag Warning
-        echo "Running Test #2: Tornado Watch / Winter WX Adv / Tornado Watch / Red Flag Warning..."
-        $CP -f test.file2 $NFILE1
-        ;;
-     3)
-        # Tornado Warning / Frost Adv / Tornado Warning
-        echo "Running Test #3: Tornado Warning / Frost Adv / Tornado Warning..."
-        $CP -f test.file3 $NFILE1
-        ;;
-     4)
-        # Frost Adv / Tornado Warning / Frost Adv / Spcl Wx / Tornado Watch / Frost Adv
-        echo "Running Test #4: Frost Adv / Tornado Warning / Frost Adv / Spcl Wx / Tornado Watch / Frost Adv..."
-        $CP -f test.file4 $NFILE1
-        ;;
-     5)
-        # Small Craft Adv / Frost Adv / Tornado Warning / Special WX * 5 / Hurricane Warning
-        echo "Running Test #5: Small Craft Adv / Frost Adv / Tornado Warning / Special WX * 5 / Hurricane Warning..."
-        $CP -f test.file5 $NFILE1
-        ;;
-     6)
-        # Flood Warning * 2
-        echo "Running Test #6: Flood Warning * 2..."
-        $CP -f test.file6 $NFILE1
-        ;;
-     7)
-        # Excessive Heat Warning / Tropical Storm Watch / Wind Chill Adv * 2
-        echo "Running Test #7: Excessive Heat Warning / Tropical Storm Watch / Wind Chill Adv * 2..."
-        $CP -f test.file7 $NFILE1
-        ;;
-     8)
-        # [Say every warning, long!, no order, can interfer with tail message playing!]
-        echo "Running Test #8: Say every warning, long, no order..."
-        $CP -f test.file8 $NFILE1
-        ;;
-     9)
-        # Single Special Weather
-        echo "Running Test #9: Single Special Weather..."
-        $CP -f test.file9 $NFILE1
-        ;;
-     *)
-        # error - ring the error bell
-        echo "TEST MODE ERROR!"
-        /usr/sbin/asterisk -rvx "rpt localplay $NODE $WXA/$A3FILE"
-        exit -89
-        ;;
+0)
+   echo 1 >/dev/null
+   ;;
+1)
+   # Tornado Watch / Tornado Warning
+   echo "Running Test #1: Tornado Watch / Tornado Warning..."
+   $CP -f test.file1 $NFILE1
+   ;;
+2)
+   # Tornado Watch / Winter WX Adv / Tornado Watch / Red Flag Warning
+   echo "Running Test #2: Tornado Watch / Winter WX Adv / Tornado Watch / Red Flag Warning..."
+   $CP -f test.file2 $NFILE1
+   ;;
+3)
+   # Tornado Warning / Frost Adv / Tornado Warning
+   echo "Running Test #3: Tornado Warning / Frost Adv / Tornado Warning..."
+   $CP -f test.file3 $NFILE1
+   ;;
+4)
+   # Frost Adv / Tornado Warning / Frost Adv / Spcl Wx / Tornado Watch / Frost Adv
+   echo "Running Test #4: Frost Adv / Tornado Warning / Frost Adv / Spcl Wx / Tornado Watch / Frost Adv..."
+   $CP -f test.file4 $NFILE1
+   ;;
+5)
+   # Small Craft Adv / Frost Adv / Tornado Warning / Special WX * 5 / Hurricane Warning
+   echo "Running Test #5: Small Craft Adv / Frost Adv / Tornado Warning / Special WX * 5 / Hurricane Warning..."
+   $CP -f test.file5 $NFILE1
+   ;;
+6)
+   # Flood Warning * 2
+   echo "Running Test #6: Flood Warning * 2..."
+   $CP -f test.file6 $NFILE1
+   ;;
+7)
+   # Excessive Heat Warning / Tropical Storm Watch / Wind Chill Adv * 2
+   echo "Running Test #7: Excessive Heat Warning / Tropical Storm Watch / Wind Chill Adv * 2..."
+   $CP -f test.file7 $NFILE1
+   ;;
+8)
+   # [Say every warning, long!, no order, can interfer with tail message playing!]
+   echo "Running Test #8: Say every warning, long, no order..."
+   $CP -f test.file8 $NFILE1
+   ;;
+9)
+   # Single Special Weather
+   echo "Running Test #9: Single Special Weather..."
+   $CP -f test.file9 $NFILE1
+   ;;
+*)
+   # error - ring the error bell
+   echo "TEST MODE ERROR!"
+   /usr/sbin/asterisk -rvx "rpt localplay $NODE $WXA/$A3FILE"
+   echo "AutoSky1 done."
+   exit -89
+   ;;
 esac
 
 # COPY ONLY ONE TYPE OF SECTION (can be multiple sections)
 #   FROM THE NWS FILE TO THE NEW FILE
-$EGREP "title" < $NFILE1 > $NFILE2
+$EGREP "title" <$NFILE1 >$NFILE2
 #
 # DOES NEW NWS FILE = OLD SAVE FILE
 #     NFILE2 suffled to NFILE2D in A*2. OK SAVE NFILE2D to FILESAVE in A*[34]
-$DIFF $NFILE2 $FILESAVE > /dev/null 2> /dev/null
+$DIFF $NFILE2 $FILESAVE >/dev/null 2>/dev/null
 Xresult="$?"
 
 # echo AutoSky1 Xresult is $Xresult
 
-case  $Xresult  in
-         0)       
-#           echo MATCH - NOTHING TO DO
-       echo "Data is the same, nothing to do..."
-	    exit 0
-            ;;
-         1)       
-#     	    echo CURRENT VS LAST MISMATCH - CHANGE ANNOUNCEMENT so CALL AutoSky2
-            echo "New data found..."
-            ./AutoSky2
-	    exit $?
-            ;;
-         2)
-#     	    echo DIFF COMMAND FAILED. Xresult was 2.
-#           echo FIGURE OUT WHAT TO DO
-            exit -92
-            ;;            
-         *)              
-#           echo BIG FAIL. Xresult was NOT 0, 1 or 2.
-	    exit -93
-esac 
-
-echo "AutoSky1 done."
+case $Xresult in
+0)
+   #           echo MATCH - NOTHING TO DO
+   echo "Data is the same, nothing to do..."
+   echo "AutoSky1 done."
+   exit 0
+   ;;
+1)
+   #     	    echo CURRENT VS LAST MISMATCH - CHANGE ANNOUNCEMENT so CALL AutoSky2
+   echo "New data found..."
+   ./AutoSky2
+   echo "AutoSky1 done."
+   exit $?
+   ;;
+2)
+   #     	    echo DIFF COMMAND FAILED. Xresult was 2.
+   #           echo FIGURE OUT WHAT TO DO
+   echo "AutoSky1 done."
+   exit -92
+   ;;
+*)
+   #           echo BIG FAIL. Xresult was NOT 0, 1 or 2.
+   echo "AutoSky1 done."
+   exit -93
+   ;;
+esac
 
 exit -94
